version: "3"
services:
  db:
    container_name: mysql_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: location
      TZ: "UTC"
    volumes:
      - ./volumes/mysql/db/:/var/lib/mysql/
    ports:
      - "3306:3306"