version: "3"
services:
  location_test_db:
    container_name: location_test_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: location
      TZ: "UTC"
    volumes:
      - ./volumes/mysql/db/:/var/lib/mysql/
    ports:
      - "3307:3306"